Update github actions main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,23 +53,23 @@ jobs:
     - name: Terraform Init
       run: terraform init
 
-    - name: Check if Resource Group Exists
+    - name: Check if Resource Group is Managed by Terraform
       id: rg-check
       run: |
-        az group show --name az-rg-1 || echo "Resource group not found"
+        terraform state list azurerm_resource_group.aks || echo "Resource group not found in state"
 
-    - name: Check if AKS Cluster Exists
-      id: aks-check
-      run: |
-        az aks show --resource-group az-rg-1 --name newlook-cluster || echo "AKS cluster not found"
-
-    - name: Import Resource Group if Exists
-      if: steps.rg-check.outputs.result == ''
+    - name: Import Resource Group if Not Managed
+      if: steps.rg-check.outputs.result == "Resource group not found in state"
       run: |
         terraform import azurerm_resource_group.aks /subscriptions/dbbcf5d5-eb47-4104-b44d-ff6bda2d8d5b/resourceGroups/az-rg-1
 
-    - name: Import AKS Cluster if Exists
-      if: steps.aks-check.outputs.result == ''
+    - name: Check if AKS Cluster is Managed by Terraform
+      id: aks-check
+      run: |
+        terraform state list azurerm_kubernetes_cluster.aks || echo "AKS cluster not found in state"
+
+    - name: Import AKS Cluster if Not Managed
+      if: steps.aks-check.outputs.result == "AKS cluster not found in state"
       run: |
         terraform import azurerm_kubernetes_cluster.aks /subscriptions/dbbcf5d5-eb47-4104-b44d-ff6bda2d8d5b/resourceGroups/az-rg-1/providers/Microsoft.ContainerService/managedClusters/newlook-cluster
 
